name: Build and Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies (optional)
        run: |
          sudo apt update
          sudo apt install -y g++ cmake make

      - name: Build
        run: |
          mkdir -p build
          cd build
          cmake ..
          make

      - name: Run tests (optional)
        run: |
          cd build
          ctest --output-on-failure
